version: '3'
services:
  node:
    container_name: hl-service-app
    restart: unless-stopped
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    environment:
      - PORT=4000
    volumes:
      - ./src:/usr/app/src
      - /usr/app/node_modules  
    networks:
      - app-network
  db:
    container_name: hl-service-db
    restart: unless-stopped
    build: ./database/
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    command: ['-c', 'logging_collector=on']
    networks:
      - app-network
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  app-network:
    driver: bridge

volumes:
  pgdata: